# Generated by Django 5.2.5 on 2025-09-20 20:37

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.URLField(blank=True, help_text="URL d'une image (jpg, jpeg, png, gif).", null=True, validators=[django.core.validators.URLValidator()])),
                ('departure_city', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_city', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('lieux_couverts', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('point_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('point_arrivee', models.CharField(blank=True, max_length=100, null=True)),
                ('is_best_trip', models.BooleanField(default=False)),
                ('points_forts', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('inclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('exclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('politique', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Monsieur'), ('Mrs', 'Madame'), ('Miss', 'Mademoiselle')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+225\\d{8,10}$', 'Numéro de téléphone invalide (format +225xxxxxxxx).')])),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='travelers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voyageur',
                'verbose_name_plural': 'Voyageurs',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backoffice.trip')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('visa_card', 'Carte Visa'), ('mobile_money', 'Mobile Money')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('canceled', 'Annulé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_expiry_month', models.CharField(blank=True, max_length=2, null=True)),
                ('card_expiry_year', models.CharField(blank=True, max_length=4, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_money_operator', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backoffice.traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backoffice.trip')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
    ]
