# Generated by Django 5.2.5 on 2025-08-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('departure_time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
    ]
