# Generated by Django 5.2.5 on 2025-09-05 21:15

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit/Debit Card')], max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry_month', models.CharField(blank=True, max_length=2, null=True)),
                ('card_expiry_year', models.CharField(blank=True, max_length=4, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Monsieur'), ('Mrs', 'Madame'), ('Ms', 'Mademoiselle')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international, par exemple +1234567890.', regex='^\\+?1?\\d{9,15}$')])),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voyageur',
                'verbose_name_plural': 'Voyageurs',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('departure_time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_best_trip', models.BooleanField(default=False)),
                ('lieux_couverts', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('point_depart', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('point_arrivee', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('points_forts', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('inclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('exclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Aucune exclusion')),
                ('politique', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
    ]
