# Generated by Django 5.1.8 on 2025-08-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('booking_date', models.DateField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_no', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=20)),
            ],
        ),
    ]
