# Generated by Django 5.2.5 on 2025-09-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Monsieur'), ('Mrs', 'Madame'), ('Ms', 'Mademoiselle')], max_length=10, null=True),
        ),
    ]
