# Generated by Django 5.2.5 on 2025-09-21 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_review_is_deleted_review_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backoffice.trip'),
        ),
    ]
