# Generated by Django 5.1.8 on 2025-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_best_trip',
            field=models.BooleanField(default=False),
        ),
    ]
