# Generated by Django 5.2.5 on 2025-09-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_review_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
