# Generated by Django 5.2.5 on 2025-08-31 13:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_trip_description_trip_exclusions_trip_inclusions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='exclusions',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Aucune exclusion'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='inclusions',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lieux_couverts',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='point_arrivee',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='point_depart',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='points_forts',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='politique',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
