# Generated by Django 5.2.5 on 2025-08-31 14:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_alter_trip_description_alter_trip_exclusions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='exclusions',
            field=tinymce.models.HTMLField(blank=True, default='Aucune exclusion'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='inclusions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='lieux_couverts',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='point_arrivee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='point_depart',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='points_forts',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='politique',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
